# Default values for metrics-app
replicaCount: 1

image:
  repository: ghcr.io/cloudraftio/metrics-app
  tag: "1.4"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

secret:
  password: "TVlQQVNTV09SRA=="

ingress:
  enabled: true
  className: "nginx"
  hosts:
    - host: metrics-app.local
      paths:
        - path: /counter
          pathType: Prefix
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 64Mi

livenessProbe:
  httpGet:
    path: /counter
    port: 8080
  initialDelaySeconds: 10
  periodSeconds: 5

readinessProbe:
  httpGet:
    path: /counter  
    port: 8080
  initialDelaySeconds: 5
  periodSeconds: 5
